### ISSUE TITLE
Spec should wait for the "result" to solve to set "current scheduling state" to null

### ISSUE THREAD

**Issue by sefeng211** [WICG/scheduling-apis#111]
The 11.2.3 at https://wicg.github.io/scheduling-apis/#schedule-a-posttask-task says to invoke "callback". This will just wait the synchronous part of the callback. 

I think the intention is to wait also for the async part of the callback to be resolved, so we should wait for "result" to be resolved before `set "current scheduling state" to null`

**Comment by mmocny** [comment]
I actually wasn't sure what Chrome does, so ran this quick little test:

```js
const start = performance.now();
await scheduler.postTask(async() => {
    await new Promise(resolve => setTimeout(resolve, 1000));
}, {delay: 1000});
const end = performance.now();
console.log(end-start); // 2000+ms
```

So, I think indeed we do wait for the task to be scheduled and fully resolved.

(I actually expected it really would be just the sync portion tbh...)

**Comment by shaseley** [comment]
Re: "current scheduling state", once the synchronous portion ends, everything should be handled by the current scheduling state being restored when microtasks run (the HostMakeCallbackJob and HostCallCallbackJob bits, if I've specced this correctly). If we kept the current state while `await`ing the result of an async callback, it could potentially be stored on unrelated promise continuations.

For example:
```js
scheduler.postTask(async () => {
  doSomething();
  // On this await call, HostMakeJobCallback is invoked, and the scheduling state stored.
  // We set the state to null to prevent it from leaking into the setTimeout below.
  await somethingAsync();
  // And here, HostCallCallbackJob is invoked, restoring the state.

  setTimeout(async () => {
    // This is a separate task, and should have a new (null) context.
    // If we don't clear the "current scheduling state", it would bind to the HostMakeJobCallback below
    // if we wait for the async outer task to clear the state.
   await scheduler.yield();
   // This shouldn't inherit from the outer postTask() since it's unrelated.
  }, 1000);

  await scheduler.postTask(() => {}, {delay: 5000});
});
```

@mmocny That behavior comes down to promise chaining: we resolve the promise `postTask()` returns with the result of the synchronous portion, which is itself a promise (because of `await`. These get chained under the hood, and the outer one (the postTask one) is now dependent on the inner one.

**Comment by brendankenny** [comment]
> @mmocny That behavior comes down to promise chaining: we resolve the promise `postTask()` returns with the result of the synchronous portion, which is itself a promise (because of `await`. These get chained under the hood, and the outer one (the postTask one) is now dependent on the inner one.

#110 is very relevant to this part :)

**Comment by mmocny** [comment]
I see, so we wait for the `return` value of the callback (or throw --> reject) but don't do any sort of "task attribution" tracking for async work spawned.  Makes perfect sense to me.

---

Updated simple test:

```js
const start = performance.now();
console.log(await scheduler.postTask(async() => {
    await new Promise(resolve => setTimeout(resolve, 1000));
    if (Math.random() > 0.5) throw "bar";
    return "foo";
}, {delay: 1000}));
const end = performance.now();
console.log(end-start); // 2000+ms
```
